Added Backend BuildSpec, Updated CloudFormation

diff --git a/buildspec_unittests.yml b/buildspec_unittests.yml
--- a/buildspec_unittests.yml
+++ b/buildspec_unittests.yml
@@ -1,35 +1,24 @@
 version: 0.2
 
-env:
-  variables:
-    IMAGE_TAG: "latest"  # Default value for the tag. Can be overridden.
-
 phases:
-  install:
-    commands:
-      - npm install
-
   pre_build:
     commands:
-      - echo "Extracting AWS Account ID from CODEBUILD_BUILD_ARN..."
-      - export ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
-      - export repository_name="hotel-app"  # Set your repository name here
-      - echo "Logging into Amazon ECR..."
-      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
+      - aws cloudformation validate-template --template-body file://backend.yml
 
   build:
     commands:
-      - echo "Building the Docker image..."
-      - docker build -t $repository_name:$IMAGE_TAG .
-      - echo "Tagging the Docker image for ECR..."
-      - docker tag $repository_name:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$repository_name:$IMAGE_TAG
-      - echo "Pushing the Docker image to ECR..."
-      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$repository_name:$IMAGE_TAG
+      - |
+        if [[ "$BRANCH_NAME" == main* ]]; then
+          DEPLOY_ENV="stage";
+        elif [[ "$BRANCH_NAME" == feature* ]]; then
+          DEPLOY_ENV="dev";
+        else
+          echo "Error: BRANCH_NAME must start with 'main' or 'feature'."
+          exit 1;
+        fi
+      - aws cloudformation deploy --template-file backend.yml --stack-name BaseInfraStack-$DEPLOY_ENV --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides Environment=$DEPLOY_ENV --no-fail-on-empty-changeset
+      - aws cloudformation wait stack-create-complete --stack-name BaseInfraStack-$DEPLOY_ENV
 
   post_build:
     commands:
-      - echo Writing image definitions file...
-      - printf '[{"name":"hotel-app","imageUri":"%s"}]' $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$repository_name:$IMAGE_TAG > imagedefinitions.json
-      
-artifacts:
-  files: imagedefinitions.json
+      - aws cloudformation describe-stacks --stack-name BaseInfraStack-$DEPLOY_ENV
